version: '2'
services:

  #  The Application
  app:
    image: 260954743274.dkr.ecr.us-east-2.amazonaws.com/academia:app
    working_dir: /var/www
    volumes:
      - /var/www/storage
    networks:
      - default
    env_file: '.env'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # The Web Server
  web:
    image: 260954743274.dkr.ecr.us-east-2.amazonaws.com/academia:web
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  # The Database
  database:
    image: mysql:5.6
    networks:
      - default
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  # redis
  cache:
    image: redis:3.0-alpine
    networks:
      - default
volumes:
  dbdata:
